apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-flask
  template:
    spec:
      containers:
        - name: k8s-flask
          image: qnix95/k8s-flask:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: development